config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'courses/developer'
  get 'courses/doctor'
  get 'courses/researcher'

  get 'webcasts/dicom_library'
  get 'webcasts/video_tutorials'
  get 'webcasts/presentations'
  get 'webcasts/dicom_viewing'
  get 'webcasts/live_chat'

  resources :welcome
  resources :doctors
  resources :courses
  resources :webcasts

  root 'welcome#index'

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception


  def after_sign_in_path_for(resource)
    logger.debug "EN EL AFTER DEL SIGN IN"
    if session[:bc_wait_action]
      create_get_events_path params: session[:bc_params]
    else
      root_path
    end
  end

  def after_sign_up_path_for(resource)
    logger.debug "EN EL AFTER DEL SIGN IN"
    if session[:bc_wait_action]
      create_get_events_path params: session[:bc_params]
    else
      root_path
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
before_action :authenticate_user!

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
before_action :authenticate_user!

  def index
    @doctors = Doctor.all
  end

  def new
  end

  def edit
  end

  def show
    @doctor = Doctor.find(params[:id])
  end

  def create
    @doctor = Doctor.new(doctor_params)
    @doctor.save
    redirect_to @doctor
  end

  private
  def doctor_params
    params.require(:doctor).permit(:name, :email, :phone, :speciality, :address)
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_filter :configure_sign_up_params, only: [:create]
 before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/webcasts_controller.rb
class WebcastsController < ApplicationController
before_action :authenticate_user!
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/webcasts_helper.rb
module WebcastsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/doctor.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Muli:400italic' rel='stylesheet' type='text/css'>
</head>
<body>
<br>
<br>

<B><p style="text-align: center; font-family: 'Muli', sans-serif; font-size: 30px;">Know our Telemedicine Courses for Doctors </p></B>

<br>

<div class="row centered">

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail course_size">
      <%= image_tag("course-doctors-1.png", :class => 'img_size')%>
      <div class="caption">
        <h3 style="text-align:center;">Use Telemedicine For</h3>
        <h1 style="text-align:center;">Create Networks</h1>
        <p style="text-align:justify;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at tortor id massa gravida faucibus eget interdum nunc. Aenean porta quis turpis ac hendrerit. Quisque bibendum mollis dolor, sit amet sollicitudin metus dictum et. Etiam congue justo tortor.</p>
        <p align="center"><a href="#" class="btn btn-primary">Preveiew</a> <a href="#" class="btn btn-default">Buy Course</a></p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail course_size">
      <%= image_tag("course-doctors-2.png", :class => 'img_size')%>
      <div class="caption">
        <h3 style="text-align:center;">Use Telemedicine For</h3>
        <h1 style="text-align:center;">Schedule for Drugs</h1>
        <p style="text-align:justify;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at tortor id massa gravida faucibus eget interdum nunc. Aenean porta quis turpis ac hendrerit. Quisque bibendum mollis dolor, sit amet sollicitudin metus dictum et. Etiam congue justo tortor.</p>
        <p align="center"><a href="#" class="btn btn-primary">Preveiew</a> <a href="#" class="btn btn-default">Buy Course</a></p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail course_size">
      <%= image_tag("course-doctors-3.png", :class => 'img_size')%>
      <div class="caption">
        <h3 style="text-align:center;">Use Telemedicine For</h3>
        <h1 style="text-align:center;">Remote Monitoring</h1>
        <p style="text-align:justify;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at tortor id massa gravida faucibus eget interdum nunc. Aenean porta quis turpis ac hendrerit. Quisque bibendum mollis dolor, sit amet sollicitudin metus dictum et. Etiam congue justo tortor.</p>
        <p align="center"><a href="#" class="btn btn-primary">Preveiew</a> <a href="#" class="btn btn-default">Buy Course</a></p>
      </div>
    </div>
  </div>

</div>

<div class="row centered">

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail course_size">
      <%= image_tag("course-doctors-4.png", :class => 'img_size')%>
      <div class="caption">
        <h3 style="text-align:center;">Use Telemedicine For</h3>
        <h1 style="text-align:center;">Data Bank</h1>
        <br><br>
        <p style="text-align:justify;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at tortor id massa gravida faucibus eget interdum nunc. Aenean porta quis turpis ac hendrerit. Quisque bibendum mollis dolor, sit amet sollicitudin metus dictum et. Etiam congue justo tortor.</p>
        <p align="center"><a href="#" class="btn btn-primary">Preveiew</a> <a href="#" class="btn btn-default">Buy Course</a></p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail course_size">
      <%= image_tag("course-doctors-5.png", :class => 'img_size')%>
      <div class="caption">
        <h3 style="text-align:center;">Use Telemedicine For</h3>
        <h1 style="text-align:center;">Permanent Observation</h1>
        <p style="text-align:justify;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at tortor id massa gravida faucibus eget interdum nunc. Aenean porta quis turpis ac hendrerit. Quisque bibendum mollis dolor, sit amet sollicitudin metus dictum et. Etiam congue justo tortor.</p>
        <p align="center"><a href="#" class="btn btn-primary">Preveiew</a> <a href="#" class="btn btn-default">Buy Course</a></p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail course_size">
      <%= image_tag("course-doctors-6.png", :class => 'img_size')%>
      <div class="caption">
        <h3 style="text-align:center;">Use Telemedicine For</h3>
        <h1 style="text-align:center;">Medical Histories</h1>
        <p style="text-align:justify;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at tortor id massa gravida faucibus eget interdum nunc. Aenean porta quis turpis ac hendrerit. Quisque bibendum mollis dolor, sit amet sollicitudin metus dictum et. Etiam congue justo tortor.</p>
        <p align="center"><a href="#" class="btn btn-primary">Preveiew</a> <a href="#" class="btn btn-default">Buy Course</a></p>
      </div>
    </div>
  </div>

</div>


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

</body>
</html>

app/views/doctors/edit.html.erb
<h1>Doctors#edit</h1>
<p>Find me in app/views/doctors/edit.html.erb</p>

app/views/doctors/index.html.erb
<style>
    h1 {
        font-family: 'Josefin Sans', sans-serif;
        margin-bottom: 20px;
        font-size: 35px;
        color: #48A5FF;
        text-align: center;
    }

     div {
         display: block;
         width: 100%;
         text-align: center;
     }
     th, td {
         width: 5%;
         font-size: large;
         text-align: center;
         border: 1px solid black;
     }
     table {
         width: 70%;
         border-collapse: collapse;
         border: 1px solid black;
         margin-left: 15%;
     }
</style>


<h1>Meet The Doctors of Our Community</h1>

<div>

  <table>
    <tr ></tr>
    <tr>
      <td colspan="7" style="background-color: #46B8DA; height: 40px;"><B>Doctors</B></td>
    </tr>
    <tr>
      <th></th>
      <th>Name</th>
      <th>E-mail</th>
      <th>Phone</th>
      <th>Speciality</th>
      <th>Address</th>
      <th>Status</th>
    </tr>
    <% @doctors.each do |doctor| %>
        <tr>
          <td><img src="assets/avatar.png"></td>
          <td><%= doctor.name %></td>
          <td><%= doctor.email %></td>
          <td><%= doctor.phone %></td>
          <td><%= doctor.speciality %></td>
          <td><%= doctor.address %></td>
          <td><%= doctor.status %></td>
        </tr>
    <% end %>
  </table>

</div>
<br><br>
<%= link_to 'Register as a New Doctor', new_doctor_path, :class => "btn btn-primary" %>

app/views/doctors/new.html.erb
<!-- Styles -->
<style type="text/css">

    body{
        padding-top: 80px;
        padding-bottom: 40px;
    }
    h2 {
        font-family: 'Josefin Sans', sans-serif;
        margin-bottom: 20px;
        line-height: 40px;
        font-size: 40px;
        color: #0094ff;
        text-align: center;
    }
    label{
        font-family: 'Josefin Sans', sans-serif;
        font-size: 16px;
        text-align: left;
        color: #080808;
        line-height: 36px;
    }
    .input{
        height: 36px !important;
        margin-bottom: 10px;
        width: 210px;
        padding-left: 10px;
        margin-left: 10px;
    }

</style>

<div class="container", style="width: 80%; margin-left: 33%;">
  <div class="row-fluid">
    <div class="span4 well" style="width: initial;">
      <label style="width: 100%;" align="center" id="txtRegStatus">
      </label>
      <h2>New Doctor</h2>
      <br />
      <%= form_for :doctor, url: doctors_path do |f| %>
          <table style='width: 100%' >
            <tr>
              <td>
                <label style="height: 100%">Name:</label>
              </td>
              <td>
                <%= f.text_field :name, autofocus: true, :class => "input" %>
              </td>
            </tr>
            <tr>
              <td>
                <label style="height: 100%">E-mail:</label>
              </td>
              <td>
                <%= f.email_field :email, autofocus: true, :class => "input" %>
              </td>
            </tr>
            <tr>
              <td>
                <label style="height: 100%">Phone:</label>
              </td>
              <td>
                <%= f.text_field :phone, autofocus: true, :class => "input" %>
              </td>
            </tr>
            <tr>
              <td>
                <label style="height: 100%">Speciality:</label>
              </td>
              <td>
                <%= f.text_field :speciality, autofocus: true, :class => "input" %>
              </td>
            </tr>
            <tr>
              <td>
                <label style="height: 100%">Address:</label>
              </td>
              <td>
                <%= f.text_field :address, autofocus: true, :class => "input" %>
              </td>
            </tr>
            <tr>
              <td colspan="2" align="right" class="actions" style="text-align: center;">
                <%= f.submit "Save", :class => "btn btn-primary", :style => "line-height: 36px, height: 36px" %>
              </td>
            </tr>
          </table>
      <% end %>
    </div>
  </div>
  <br />
</div>

app/views/doctors/show.html.erb
<!-- Styles -->
<style type="text/css">

    body{
        padding-top: 80px;
        padding-bottom: 40px;
    }
    h2 {
        font-family: 'Josefin Sans', sans-serif;
        margin-bottom: 20px;
        line-height: 40px;
        font-size: 40px;
        color: #0094ff;
        text-align: center;
    }
    label{
        font-family: 'Josefin Sans', sans-serif;
        font-size: 16px;
        text-align: left;
        color: #080808;
        line-height: 36px;
    }
    .input{
        height: 36px !important;
        margin-bottom: 10px;
        width: 210px;
        padding-left: 10px;
        margin-left: 10px;
    }

</style>

<div class="container", style="width: 80%; margin-left: 33%;">
  <div class="row-fluid">
    <div class="span4 well" style="width: initial;">
      <label style="width: 100%;" align="center" id="txtRegStatus">
      </label>
      <h2>New Doctor</h2>
      <br />
      <%= form_for :doctor, url: doctors_path do |f| %>
          <table style='width: 100%' >
            <tr>
              <td>
                <label style="height: 100%">Name:</label>
              </td>
              <td>
                <%= @doctor.name %>
              </td>
            </tr>
            <tr>
              <td>
                <label style="height: 100%">E-mail:</label>
              </td>
              <td>
                <%= @doctor.email %>
              </td>
            </tr>
            <tr>
              <td>
                <label style="height: 100%">Phone:</label>
              </td>
              <td>
                <%= @doctor.phone %>>
              </td>
            </tr>
            <tr>
              <td>
                <label style="height: 100%">Speciality:</label>
              </td>
              <td>
                <%= @doctor.speciality %>
              </td>
            </tr>
            <tr>
              <td>
                <label style="height: 100%">Address:</label>
              </td>
              <td>
                <%= @doctor.address %>
              </td>
            </tr>
            <tr>
              <td colspan="2" align="right" class="actions" style="text-align: center;">
                <%= link_to 'Doctors', doctors_path, :class => "btn btn-primary" %>
              </td>
            </tr>
          </table>
      <% end %>
    </div>
  </div>
  <br />
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <title>Telemedicine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application',media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <style>
      .navbar-default .navbar-nav > li > a {
          color: #FFF;
          padding-top: 0px;
          line-height: 50px;
      }

  </style>
</head>
<body>

<!-- Header -->
<div id="header" class="navbar navbar-default navbar-fixed-top">
  <nav class="collapse navbar-collapse">
    <ul class="nav navbar-nav", style="padding-left: 18px;">
      <li><%= image_tag("logo.png", width: "65px", height:"50px")%></li>
      <li><p style="font-family: 'Pacifico', cursive; font-size: 30px; margin-top: 10px; padding-left: 19.625px;  line-height: 100%;">Click</p></li>
      <li style="padding-left: 19.625px;"><a href="/">Home</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Courses<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Courses for Doctors', courses_doctor_path %></li>
          <li><%= link_to 'Courses for Developers', courses_developer_path %></li>
          <li><%= link_to 'Courses for Researchers', courses_researcher_path %></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Webcasts<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">LMS</a></li>
          <li><a href="#">Skill-Gap</a></li>
          <li><a href="#">Webinar</a></li>
          <li><a href="#">Documentation</a></li>
          <li><%= link_to 'Video Tutorials', "/webcasts/video_tutorials" %></li>
          <li><%= link_to 'Presentations', "/webcasts/presentations" %></li>
          <li><%= link_to 'DICOM Library', "/webcasts/dicom_library" %></li>
          <li><%= link_to 'DICOM Remote Viewing', "/webcasts/dicom_viewing" %></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Contact Us<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="/doctors">Our Community</a></li>
          <li><a href="#">By Email</a></li>
          <li><a href="#">Video Conferencing</a></li>
          <li><a href="#">Webchat</a></li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav pull-right" , style="padding-right: 18px;">
      <li class="dropdown-toggle">
        <a href="" title="View or edit Board."><i class="ion-ios-browsers-outline", style="font-size: 40px"></i></a>
      </li>
      <li class="dropdown-toggle">
        <!--%= link_to '', webcasts_live_chat_path, :class => "ion-ios-chatboxes-outline", :style => "font-size: 40px;" %-->
        <a href="/webcasts/live_chat" title="Live chat."><i class="ion-ios-chatboxes-outline", style="font-size: 40px"></i></a>
      </li>
      <li class="dropdown-toggle">
        <a href="" title="Get pricing and make purchases."><i class="ion-ios-cart-outline", style="font-size: 40px"></i></a>
      </li>
      <li class="dropdown-toggle">
        <%= link_to '', new_user_registration_path, :title => "Sign in to get pricing, save your Boards and more. Get all the benefits of being a registered user.", :class => "ion-ios-person-outline", :style => "font-size: 40px;" %>
      </li>
      <% if user_signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        </ul>
      </li>
      <% end %>
    </ul>
  </nav>
</div>
<!-- Fin de la Barra a 100% -->

<!-- Contenido-->
<div class="contenedor-total" style="width: 100%;"> <!-- 1024px -->

  <section>
    <%= yield %>
  </section>
  <!-- fin de contenido izq -->
</div>
<div class="limpiar"></div>
<!-- fin de Contenido-->

<div style="clear:both;"></div>

<!-- Footer  -->
<!--footer id="footer">
  <div class="column-container">
    <div class="col-md-9">
      <p style="color: #fff; text-align: center;">All contents © copyright 2015-2025 Health On A Click. All rights reserved; Designed & Developed By:<a href="">Patry's Health Consortium</a></p>
    </div>
    <div class="col-md-3">
      <form class="languages go" method="get" action="/es/docs/Web">
        <label style="padding-right: 5px;">Languajes:</label>
        <select id="language" class="wiki-l10n" name="next" dir="ltr">
          <option>English (US)</option>
          <option>Spanish</option>
          <option>Français</option>
          <option>Português (do&nbsp;Brasil)</option>
          <option>Deutsch</option>
          <option>Italian</option>
        </select>
      </form>
    </div>
  </div>
</footer-->
<!-- fin de Footer  -->

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/webcasts/dicom_library.html.erb
<link href='http://fonts.googleapis.com/css?family=Muli:400italic' rel='stylesheet' type='text/css'>
<style>
    buttom {
        height: 36px !important;
        margin-bottom: 5px;
    }
</style>

<B><p style="text-align: center; font-family: 'Muli', sans-serif; font-size: 30px; color: #23527c">DICOM Library Service </p></B>

<p style="text-align: justify; font-family: 'Muli', sans-serif; font-size: 17px; padding: 25px;">Digital Imaging and Communications in Medicine (DICOM) is a standard for handling, storing, printing, and transmitting information in medical imaging. It includes a file format definition and a network communications protocol. The communication protocol is an application protocol that uses TCP/IP to communicate between systems. DICOM files can be exchanged between two entities that are capable of receiving image and patient data in DICOM format. </p>

<div class="owl-carousel" id="owl-demo">
  <div class="item"><img class="dicom_corousel_img" src="/assets/DICOM-Image-1.png"></div>
  <div class="item"><img class="dicom_corousel_img" src="/assets/DICOM-Image-2.png"></div>
  <div class="item"><img class="dicom_corousel_img" src="/assets/DICOM-Image-3.png"></div>
  <div class="item"><img class="dicom_corousel_img" src="/assets/DICOM-Image-4.png"></div>
  <div class="item"><img class="dicom_corousel_img" src="/assets/DICOM-Image-5.jpg"></div>
  <div class="item"><img class="dicom_corousel_img" src="/assets/DICOM-Image-6.jpg"></div>
  <div class="item"><img class="dicom_corousel_img" src="/assets/DICOM-Image-1.png"></div>
  <div class="item"><img class="dicom_corousel_img" src="/assets/DICOM-Image-2.png"></div>
  <div class="item"><img class="dicom_corousel_img" src="/assets/DICOM-Image-3.png"></div>
  <div class="item"><img class="dicom_corousel_img" src="/assets/DICOM-Image-4.png"></div>
  <div class="item"><img class="dicom_corousel_img" src="/assets/DICOM-Image-5.jpg"></div>
  <div class="item"><img class="dicom_corousel_img" src="/assets/DICOM-Image-6.jpg"></div>
</div>

<br>

<div style="text-align: center;">
<%= link_to 'DICOM Remote Viewing', webcasts_dicom_viewing_path, :class => "btn btn-primary" %>
</div>

<script>
    $("#owl-demo").owlCarousel({
        autoPlay: 3000, //Set AutoPlay to 3 seconds
        items : 4,
        itemsDesktop : [1199,3],
        itemsDesktopSmall : [979,3],
    })
</script>

<br><br><br><br><br><br><br><br><br>
